export const categories = [
  "Transport de colis",
  "Vidange de voiture",
  "Peinture murale",
  "Pose de plafond",
  "Pose de papier peint",
  "Réparation de lave-vaisselle",
  "Pose de tringle à rideaux",
  "Débarras de cave",
  "Récupération de colis",
  "Réparation de machine à laver",
  "Sol à peindre",
  "Montage de cuisine en kit",
  "Achat de courses",
  "Garde de bébé",
  "Pose de placo",
  "Évacuation de déchets",
  "Récupération de table",
  "Entretien de jardin",
  "Débroussaillage de jardin",
  "Pose de prise électrique",
  "Bricolage et petits travaux",
  "Réparation de voiture",
  "Plomberie et installation sanitaire",
  "Déménagement",
  "Femme de ménage",
  "Installation électrique",
  "Peinture et tapisserie",
  "Maçonnerie",
  "Dépannage électroménager",
  "Menuiserie, huisserie et agencement",
  "Livraison et transport de colis",
  "Jardinier",
  "Évacuation de déchets et gravats",
  "Montage de meubles en kit",
  "Tonte de pelouse et débroussaillage",
  "Plâtrerie, murs et plafonds",
  "Carrelage",
  "Manutention",
  "Paysagiste et aménagement du jardin",
  "Terrassement et assainissement",
];

const serviceNames = [
  "Plomberie",
  "Électricité",
  "Serrurerie",
  "Bricolage",
  "Nettoyage",
  "Peinture",
  "Lavage auto",
];

export const professions = [...serviceNames, ...categories];
